### ISSUE TITLE
Missing `data` for ClassCharts Parent Login

### ISSUE THREAD

**Issue by veloii** [classchartsapi/api-docs#2]
If you have a ClassCharts Parent account, we'd love if you could us send your response (a redacted version of course) to the `https://www.classcharts.com/apiv2parent/login` (edited) endpoint.

You can find more information on how to interact with these endpoint on the API documentation.

**Comment by IsaacHatton** [comment]
I can't seem to get the endpoint to work, is this 
![image](https://github.com/classchartsapi/api-docs/assets/74068072/fc645fe3-a391-45a2-8361-6b5063a42030)

Also, DevTools doesn't seem to show a connection to this endpoint during a successful parent login.

**Comment by veloii** [comment]
Hi, my apologies, the endpoint should be `https://www.classcharts.com/apiv2parent/login`.

**Comment by IsaacHatton** [comment]
{
    "success": 1,
    "data": {
        "id": 1234567,
        "name": "John Smith",
        "email": "jsmith@example.com",
        "language": null,
        "isEmailVerified": true
    },
    "meta": {
        "session_id": "1234567890abcdef1234567890abcdef"
    }
}

**Comment by veloii** [comment]
Thank you! I'll update the docs.
