### ISSUE TITLE
A date is not required to get list of lessons

### ISSUE THREAD

**Issue by StupidRepo** [classchartsapi/api-docs#3]
On [the List Lessons page](https://classchartsapi.github.io/api-docs/client-api/operations/list-lessons/), it mentions that `date` is required. However, if no `date` parameter is specified, it will use the current day at the time of that request :)

I would remove this required tag myself and create a PR however I'm not sure how to do that for these docs, so I decided I'd create an issue and leave the rest to the professionals, lol.

Also, thanks for making this! At the current time of writing, it's the holidays (in the UK) and all of my timetable data has been removed so I can't check the response and format of the timetable endpoint. These docs has helped significantly with a project I've been working on over the holidays (as most other data is wiped too like all detentions). I, of course, don't want to advertise this project here but if you're interested I can respond with a link to it (or you can probably guess it by looking at my profile lol).

**Comment by jamesatjaminit** [comment]
Updated the docs. The website should update shortly :). Thanks for the kind words, it's mostly the work of @veloii. I look forward to seeing your project :)

**Comment by StupidRepo** [comment]
> Thanks for the kind words, it's mostly the work of @veloii.

No problem!

> I look forward to seeing your project :)

I just hope a ClassCharts dev sees it and wants to put it on the Google Play Store, lol.
